version: "3"
services:
  postgres:
    build:
      context: ./docker/postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'Skrifter'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
  api:
    build:
      context: "./docker/api"
    ports:
      - "8080:8080"
    volumes:
      - "./api:/srv"
  nginx:
    build:
      context: "./docker/nginx"
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
  storage:
    build:
      context: "./docker/storage"
    ports:
      - "8000:8000"
    volumes:
      - "./storage:/srv"
  mongo:
    build:
      context: "./docker/mongo"
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  frontend:
    build:
      context: "./docker/frontend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/srv"