version: "3"
services:
  postgres:
    build:
      context: ./docker/postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'Skrifter'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
  api:
    build:
      context: "./docker/api"
    ports:
      - "8080:8080"
    volumes:
      - "./api:/srv"
  nginx:
    build:
      context: "./docker/nginx"
    ports:
      - "80:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"